### ISSUE TITLE
我覺得需求那邊可以把 python 和 selenium 刪掉

### ISSUE THREAD

**Issue by joremysh** [penut85420/TranslationImprover#1]
或者是另外在 github 以外的平台用 blog 文章之類的，把 readme 貼過去再把 python 和 selenium 刪掉。

因為你的 exe 檔案應該是已經把 python 包好了，所以對於只會 exe 點兩下執行的人來說，應該不需要裝這些就可以用？對這種人來說看到可能就會有心理障礙。

**Comment by penut85420** [comment]
@JeremyShih 感謝提供意見！這兩天我會抽空處理一下，不過我沒有經營部落格的經驗，我可能會試試看用 GitHub Pages 的方式來製作說明文章，另外我也會把 WebDriver 也包進 Release 的壓縮檔裡面試試看

**Comment by joremysh** [comment]
感覺在 HackMD 加一頁就可以了？

**Comment by penut85420** [comment]
HackMD 的部分我應該會把 GitHub 連結附上，這裡設定成 GitHub Page 看看，感謝！
